# NumPy Problems

In [520]:
import numpy as np
from numpy.linalg import norm
import csv

In [521]:
with open('auto-mpg.csv', 'r') as file:
    reader = csv.reader(file)
    data = list(reader)

In [522]:
data[0]

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [523]:
data

[['mpg',
  'cylinders',
  'displacement',
  'horsepower',
  'weight',
  'acceleration',
  'model year',
  'origin',
  'car name'],
 ['18',
  '8',
  '307',
  '130',
  '3504',
  '12',
  '70',
  '1',
  'chevrolet chevelle malibu'],
 ['15', '8', '350', '165', '3693', '11.5', '70', '1', 'buick skylark 320'],
 ['18', '8', '318', '150', '3436', '11', '70', '1', 'plymouth satellite'],
 ['16', '8', '304', '150', '3433', '12', '70', '1', 'amc rebel sst'],
 ['17', '8', '302', '140', '3449', '10.5', '70', '1', 'ford torino'],
 ['15', '8', '429', '198', '4341', '10', '70', '1', 'ford galaxie 500'],
 ['14', '8', '454', '220', '4354', '9', '70', '1', 'chevrolet impala'],
 ['14', '8', '440', '215', '4312', '8.5', '70', '1', 'plymouth fury iii'],
 ['14', '8', '455', '225', '4425', '10', '70', '1', 'pontiac catalina'],
 ['15', '8', '390', '190', '3850', '8.5', '70', '1', 'amc ambassador dpl'],
 ['15', '8', '383', '170', '3563', '10', '70', '1', 'dodge challenger se'],
 ['14', '8', '340', '160', '3609', 

## 1. Basic Array Operations
- Convert the mpg column into a NumPy array and calculate:The mean, median, and standard deviation of mpg.
- The number of cars with mpg greater than 25.

In [524]:
mpg_data = np.array([data[i][0] for i in range(1,len(data))]).astype('float64')
mpg_data

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [525]:
print("Mean of mpg = ", np.mean(mpg_data))
print("Median of mpg = ", np.median(mpg_data))
print("Standard deviation of mpg = ", np.std(mpg_data))
print("Number of cars with mpg>25 = ", np.count_nonzero(mpg_data>25))

Mean of mpg =  23.514572864321607
Median of mpg =  23.0
Standard deviation of mpg =  7.806159061274433
Number of cars with mpg>25 =  158


## 2. Filtering
Using NumPy, filter all cars with more than 6 cylinders.  
Return the corresponding car name as a list.

In [526]:
cylinder_data = np.array([data[i][1] for i in range(1,len(data))]).astype('int')
car_name_data = np.array([data[i][8] for i in range(1,len(data))])
for i in range(len(cylinder_data)):
    print(cylinder_data[i], car_name_data[i])

8 chevrolet chevelle malibu
8 buick skylark 320
8 plymouth satellite
8 amc rebel sst
8 ford torino
8 ford galaxie 500
8 chevrolet impala
8 plymouth fury iii
8 pontiac catalina
8 amc ambassador dpl
8 dodge challenger se
8 plymouth 'cuda 340
8 chevrolet monte carlo
8 buick estate wagon (sw)
4 toyota corona mark ii
6 plymouth duster
6 amc hornet
6 ford maverick
4 datsun pl510
4 volkswagen 1131 deluxe sedan
4 peugeot 504
4 audi 100 ls
4 saab 99e
4 bmw 2002
6 amc gremlin
8 ford f250
8 chevy c20
8 dodge d200
8 hi 1200d
4 datsun pl510
4 chevrolet vega 2300
4 toyota corona
4 ford pinto
6 amc gremlin
6 plymouth satellite custom
6 chevrolet chevelle malibu
6 ford torino 500
6 amc matador
8 chevrolet impala
8 pontiac catalina brougham
8 ford galaxie 500
8 plymouth fury iii
8 dodge monaco (sw)
8 ford country squire (sw)
8 pontiac safari (sw)
6 amc hornet sportabout (sw)
4 chevrolet vega (sw)
6 pontiac firebird
6 ford mustang
4 mercury capri 2000
4 opel 1900
4 peugeot 304
4 fiat 124b
4 toyota corol

In [527]:
car_with_more_than_6_cylinders = [car_name_data[i] for i in range(len(car_name_data)) if cylinder_data[i]>6 ]
print("Cars with with more than 6 cylinders = ", len(car_with_more_than_6_cylinders))

Cars with with more than 6 cylinders =  103


In [528]:
car_with_more_than_6_cylinders

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

## 3. Statistical Analysis
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [529]:
weight_data = np.array([data[i][4] for i in range(1,len(data))]).astype('int')
weight_data

array([3504, 3693, 3436, 3433, 3449, 4341, 4354, 4312, 4425, 3850, 3563,
       3609, 3761, 3086, 2372, 2833, 2774, 2587, 2130, 1835, 2672, 2430,
       2375, 2234, 2648, 4615, 4376, 4382, 4732, 2130, 2264, 2228, 2046,
       2634, 3439, 3329, 3302, 3288, 4209, 4464, 4154, 4096, 4955, 4746,
       5140, 2962, 2408, 3282, 3139, 2220, 2123, 2074, 2065, 1773, 1613,
       1834, 1955, 2278, 2126, 2254, 2408, 2226, 4274, 4385, 4135, 4129,
       3672, 4633, 4502, 4456, 4422, 2330, 3892, 4098, 4294, 4077, 2933,
       2511, 2979, 2189, 2395, 2288, 2506, 2164, 2100, 4100, 3672, 3988,
       4042, 3777, 4952, 4464, 4363, 4237, 4735, 4951, 3821, 3121, 3278,
       2945, 3021, 2904, 1950, 4997, 4906, 4654, 4499, 2789, 2279, 2401,
       2379, 2124, 2310, 2472, 2265, 4082, 4278, 1867, 2158, 2582, 2868,
       3399, 2660, 2807, 3664, 3102, 2875, 2901, 3336, 1950, 2451, 1836,
       2542, 3781, 3632, 3613, 4141, 4699, 4457, 4638, 4257, 2219, 1963,
       2300, 1649, 2003, 2125, 2108, 2246, 2489, 23

In [530]:
print("25th percentile of weight column = ", np.percentile(weight_data,25))
print("50th percentile of weight column = ", np.percentile(weight_data,50))
print("75th percentile of weight column = ", np.percentile(weight_data,75))

25th percentile of weight column =  2223.75
50th percentile of weight column =  2803.5
75th percentile of weight column =  3608.0


## 4. Array Manipulation
Convert the acceleration column into a NumPy array and normalize its values (scale between 0 and 1).

In [531]:
acceleration_data = np.array([data[i][5] for i in range(1,len(data))]).astype('float64')
acceleration_data

array([12. , 11.5, 11. , 12. , 10.5, 10. ,  9. ,  8.5, 10. ,  8.5, 10. ,
        8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5, 14.5,
       17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. , 19. ,
       13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. , 11.5, 12. ,
       12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5, 19. , 18. ,
       19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. , 13.5, 13. ,
       11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. , 14. , 14.5,
       18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. , 11.5, 13. ,
       14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. , 16.5, 18. ,
       16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. , 19. , 19.5,
       16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5, 14. , 15.5,
       11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. , 16.5, 21. ,
       17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5, 16.5, 15.5,
       14.5, 16.5, 19. , 14.5, 15.5, 14. , 15. , 15

In [532]:
normalised_acceleration_data = acceleration_data/norm(acceleration_data)
print("Normalised acceleration values = \n", normalised_acceleration_data)

Normalised acceleration values = 
 [0.03804627 0.03646101 0.03487575 0.03804627 0.03329049 0.03170523
 0.0285347  0.02694944 0.03170523 0.02694944 0.03170523 0.02536418
 0.03011997 0.03170523 0.04755784 0.0491431  0.0491431  0.05072836
 0.04597258 0.06499572 0.05548415 0.04597258 0.05548415 0.03963153
 0.04755784 0.04438732 0.04755784 0.04280206 0.05865467 0.04597258
 0.0491431  0.04438732 0.06023993 0.0412168  0.0491431  0.0491431
 0.0491431  0.0491431  0.03804627 0.03646101 0.04280206 0.0412168
 0.03646101 0.03804627 0.03804627 0.04280206 0.06023993 0.04755784
 0.04597258 0.04438732 0.04438732 0.06182519 0.04597258 0.06023993
 0.05706941 0.06023993 0.06499572 0.0491431  0.05389889 0.07450728
 0.06182519 0.05231362 0.03804627 0.03804627 0.04280206 0.0412168
 0.03646101 0.03487575 0.04280206 0.04280206 0.03963153 0.04280206
 0.03963153 0.04438732 0.05072836 0.04438732 0.04597258 0.05706941
 0.06182519 0.05706941 0.05072836 0.05389889 0.04597258 0.04755784
 0.05231362 0.0412168  0.03646

In [533]:
normalised_acceleration_data_min_max = (acceleration_data-np.min(acceleration_data))/(np.max(acceleration_data)-np.min(acceleration_data))
print("Normalised acceleration values using min-max scaling = \n", normalised_acceleration_data_min_max)

Normalised acceleration values using min-max scaling = 
 [0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619  0.11904762 0.
 0.08928571 0.11904762 0.41666667 0.44642857 0.44642857 0.47619048
 0.38690476 0.74404762 0.56547619 0.38690476 0.56547619 0.26785714
 0.41666667 0.35714286 0.41666667 0.32738095 0.625      0.38690476
 0.44642857 0.35714286 0.6547619  0.29761905 0.44642857 0.44642857
 0.44642857 0.44642857 0.23809524 0.20833333 0.32738095 0.29761905
 0.20833333 0.23809524 0.23809524 0.32738095 0.6547619  0.41666667
 0.38690476 0.35714286 0.35714286 0.68452381 0.38690476 0.6547619
 0.5952381  0.6547619  0.74404762 0.44642857 0.53571429 0.92261905
 0.68452381 0.50595238 0.23809524 0.23809524 0.32738095 0.29761905
 0.20833333 0.17857143 0.32738095 0.32738095 0.26785714 0.32738095
 0.26785714 0.35714286 0.47619048 0.35714286 0.38690476 0.5952381
 0.68452381 0.5952381  0.47619048 0.53571429 0.38690476 0.41666667
 0.50595238 0.2

## 5. Broadcasting
Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.

In [534]:
horse_power_data = np.array([data[i][3] for i in range(1,len(data))])
horse_power_data

array(['130', '165', '150', '150', '140', '198', '220', '215', '225',
       '190', '170', '160', '150', '225', '95', '95', '97', '85', '88',
       '46', '87', '90', '95', '113', '90', '215', '200', '210', '193',
       '88', '90', '95', '?', '100', '105', '100', '88', '100', '165',
       '175', '153', '150', '180', '170', '175', '110', '72', '100', '88',
       '86', '90', '70', '76', '65', '69', '60', '70', '95', '80', '54',
       '90', '86', '165', '175', '150', '153', '150', '208', '155', '160',
       '190', '97', '150', '130', '140', '150', '112', '76', '87', '69',
       '86', '92', '97', '80', '88', '175', '150', '145', '137', '150',
       '198', '150', '158', '150', '215', '225', '175', '105', '100',
       '100', '88', '95', '46', '150', '167', '170', '180', '100', '88',
       '72', '94', '90', '85', '107', '90', '145', '230', '49', '75',
       '91', '112', '150', '110', '122', '180', '95', '?', '100', '100',
       '67', '80', '65', '75', '100', '110', '105', '140', '1

In [535]:
mean_sum = 0
count = 0
for i in range(len(horse_power_data)):
    if(horse_power_data[i] != '?'):
        count += 1
        mean_sum += horse_power_data[i].astype('int')
mean = mean_sum/count

for i in range(len(horse_power_data)):
    if(horse_power_data[i] == '?'):
        horse_power_data[i] = np.round(mean)

horse_power_data = horse_power_data.astype('int')

horse_power_data

array([130, 165, 150, 150, 140, 198, 220, 215, 225, 190, 170, 160, 150,
       225,  95,  95,  97,  85,  88,  46,  87,  90,  95, 113,  90, 215,
       200, 210, 193,  88,  90,  95, 104, 100, 105, 100,  88, 100, 165,
       175, 153, 150, 180, 170, 175, 110,  72, 100,  88,  86,  90,  70,
        76,  65,  69,  60,  70,  95,  80,  54,  90,  86, 165, 175, 150,
       153, 150, 208, 155, 160, 190,  97, 150, 130, 140, 150, 112,  76,
        87,  69,  86,  92,  97,  80,  88, 175, 150, 145, 137, 150, 198,
       150, 158, 150, 215, 225, 175, 105, 100, 100,  88,  95,  46, 150,
       167, 170, 180, 100,  88,  72,  94,  90,  85, 107,  90, 145, 230,
        49,  75,  91, 112, 150, 110, 122, 180,  95, 104, 100, 100,  67,
        80,  65,  75, 100, 110, 105, 140, 150, 150, 140, 150,  83,  67,
        78,  52,  61,  75,  75,  75,  97,  93,  67,  95, 105,  72,  72,
       170, 145, 150, 148, 110, 105, 110,  95, 110, 110, 129,  75,  83,
       100,  78,  96,  71,  97,  97,  70,  90,  95,  88,  98, 11

In [536]:
increased_horse_power_data = horse_power_data+horse_power_data*0.1
print("Increased horsepower (+10%) = \n", increased_horse_power_data)

Increased horsepower (+10%) = 
 [143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209.  187.  176.
 165.  247.5 104.5 104.5 106.7  93.5  96.8  50.6  95.7  99.  104.5 124.3
  99.  236.5 220.  231.  212.3  96.8  99.  104.5 114.4 110.  115.5 110.
  96.8 110.  181.5 192.5 168.3 165.  198.  187.  192.5 121.   79.2 110.
  96.8  94.6  99.   77.   83.6  71.5  75.9  66.   77.  104.5  88.   59.4
  99.   94.6 181.5 192.5 165.  168.3 165.  228.8 170.5 176.  209.  106.7
 165.  143.  154.  165.  123.2  83.6  95.7  75.9  94.6 101.2 106.7  88.
  96.8 192.5 165.  159.5 150.7 165.  217.8 165.  173.8 165.  236.5 247.5
 192.5 115.5 110.  110.   96.8 104.5  50.6 165.  183.7 187.  198.  110.
  96.8  79.2 103.4  99.   93.5 117.7  99.  159.5 253.   53.9  82.5 100.1
 123.2 165.  121.  134.2 198.  104.5 114.4 110.  110.   73.7  88.   71.5
  82.5 110.  121.  115.5 154.  165.  165.  154.  165.   91.3  73.7  85.8
  57.2  67.1  82.5  82.5  82.5 106.7 102.3  73.7 104.5 115.5  79.2  79.2
 187.  159.5 165.  162.8

## 6. Boolean Indexing
Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing.

In [537]:
displacement_data = np.array([data[i][2] for i in range(1,len(data))])
origin_data = np.array([data[i][7] for i in range(1,len(data))]).astype('int')
for i in range(len(displacement_data)):
    print(displacement_data[i], origin_data[i])

307 1
350 1
318 1
304 1
302 1
429 1
454 1
440 1
455 1
390 1
383 1
340 1
400 1
455 1
113 3
198 1
199 1
200 1
97 3
97 2
110 2
107 2
104 2
121 2
199 1
360 1
307 1
318 1
304 1
97 3
140 1
113 3
98 1
232 1
225 1
250 1
250 1
232 1
350 1
400 1
351 1
318 1
383 1
400 1
400 1
258 1
140 1
250 1
250 1
122 1
116 2
79 2
88 2
71 3
72 3
97 2
91 1
113 3
97.5 1
97 2
140 1
122 1
350 1
400 1
318 1
351 1
304 1
429 1
350 1
350 1
400 1
70 3
304 1
307 1
302 1
318 1
121 2
121 2
120 2
96 2
122 1
97 3
120 3
98 1
97 3
350 1
304 1
350 1
302 1
318 1
429 1
400 1
351 1
318 1
440 1
455 1
360 1
225 1
250 1
232 1
250 1
198 1
97 2
400 1
400 1
360 1
350 1
232 1
97 3
140 1
108 3
70 3
122 1
155 1
98 2
350 1
400 1
68 2
116 2
114 2
121 2
318 1
121 2
156 3
350 1
198 1
200 1
232 1
250 1
79 3
122 1
71 3
140 1
250 1
258 1
225 1
302 1
350 1
318 1
302 1
304 1
98 2
79 2
97 2
76 3
83 3
90 1
90 2
116 2
120 3
108 3
79 2
225 1
250 1
250 1
250 1
400 1
350 1
318 1
351 1
231 1
250 1
258 1
225 1
231 1
262 1
302 1
97 3
140 1
232 1
140 1
134 3

In [538]:
origin_boolean_mask = origin_data == 2
origin_boolean_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True,  True,  True,  True, False,  True, False, False, False,
       False, False,

In [539]:
print("Average displacement of cars with origin 2 (Europe) = ", np.round(np.mean(displacement_data[origin_boolean_mask].astype('float64')),2))

Average displacement of cars with origin 2 (Europe) =  109.14


## 7. Matrix Operations
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.  
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [540]:
d2_array = np.array([mpg_data, horse_power_data, weight_data])
print(d2_array)
print(d2_array.shape)

[[  18.   15.   18. ...   32.   28.   31.]
 [ 130.  165.  150. ...   84.   79.   82.]
 [3504. 3693. 3436. ... 2295. 2625. 2720.]]
(3, 398)


In [541]:
vector = np.array([1, 0.5, -0.2])
print(vector)
print(vector.shape)

[ 1.   0.5 -0.2]
(3,)


In [542]:
dot_product = np.dot(vector,d2_array)
print("Dot product = ", dot_product)
print(dot_product.shape)

Dot product =  [-617.8 -641.1 -594.2 -595.6 -602.8 -754.2 -746.8 -740.9 -758.5 -660.
 -612.6 -627.8 -662.2 -490.7 -402.9 -497.1 -488.3 -453.9 -355.  -318.
 -465.9 -417.  -402.5 -364.3 -463.6 -805.5 -765.2 -760.4 -840.9 -355.
 -379.8 -373.1 -332.2 -457.8 -619.3 -598.8 -597.4 -589.6 -745.3 -791.3
 -740.3 -730.2 -889.  -851.2 -927.5 -519.4 -423.6 -587.4 -565.8 -378.
 -351.6 -349.8 -345.  -291.1 -253.1 -309.8 -330.  -384.1 -360.2 -400.8
 -416.6 -381.2 -759.3 -775.5 -737.  -735.3 -642.4 -811.6 -809.9 -799.2
 -776.4 -398.5 -688.4 -741.6 -775.8 -726.4 -512.6 -442.2 -531.3 -377.3
 -414.  -383.6 -429.7 -364.8 -349.  -719.5 -645.4 -712.1 -725.9 -665.4
 -879.4 -804.8 -780.6 -758.4 -826.5 -865.7 -663.7 -553.7 -589.6 -521.
 -542.2 -510.3 -341.  -913.4 -885.7 -832.8 -797.8 -489.8 -391.8 -423.2
 -406.8 -361.8 -400.5 -419.9 -382.  -728.9 -724.6 -319.9 -370.1 -450.9
 -498.6 -589.8 -453.  -480.4 -631.8 -552.9 -502.  -511.2 -602.2 -325.5
 -424.2 -302.7 -445.9 -690.2 -655.4 -652.1 -742.2 -851.8 -802.4 -84

## 8. Sorting
Use NumPy to sort the cars by model_year in descending order and display the first five car names.

In [543]:
model_year_data = np.array([data[i][6] for i in range(1,len(data))])
model_year_car_name_data = np.array([model_year_data, car_name_data])
model_year_car_name_data

array([['70', '70', '70', '70', '70', '70', '70', '70', '70', '70', '70',
        '70', '70', '70', '70', '70', '70', '70', '70', '70', '70', '70',
        '70', '70', '70', '70', '70', '70', '70', '71', '71', '71', '71',
        '71', '71', '71', '71', '71', '71', '71', '71', '71', '71', '71',
        '71', '71', '71', '71', '71', '71', '71', '71', '71', '71', '71',
        '71', '71', '72', '72', '72', '72', '72', '72', '72', '72', '72',
        '72', '72', '72', '72', '72', '72', '72', '72', '72', '72', '72',
        '72', '72', '72', '72', '72', '72', '72', '72', '73', '73', '73',
        '73', '73', '73', '73', '73', '73', '73', '73', '73', '73', '73',
        '73', '73', '73', '73', '73', '73', '73', '73', '73', '73', '73',
        '73', '73', '73', '73', '73', '73', '73', '73', '73', '73', '73',
        '73', '73', '73', '73', '74', '74', '74', '74', '74', '74', '74',
        '74', '74', '74', '74', '74', '74', '74', '74', '74', '74', '74',
        '74', '74', '74', '74', '74', 

In [544]:
desc_sorted_model_year_car_name_data = np.sort(np.column_stack(([model_year_data, car_name_data])))[::-1]
desc_sorted_model_year_car_name_data

array([['82', 'chevy s-10'],
       ['82', 'ford ranger'],
       ['82', 'dodge rampage'],
       ['82', 'vw pickup'],
       ['82', 'ford mustang gl'],
       ['82', 'chevrolet camaro'],
       ['82', 'dodge charger 2.2'],
       ['82', 'toyota celica gt'],
       ['82', 'ford granada l'],
       ['82', 'chrysler lebaron medallion'],
       ['82', 'oldsmobile cutlass ciera (diesel)'],
       ['82', 'buick century limited'],
       ['82', 'datsun 310 gx'],
       ['82', 'honda civic (auto)'],
       ['82', 'honda civic'],
       ['82', 'toyota corolla'],
       ['82', 'honda accord'],
       ['82', 'nissan stanza xe'],
       ['82', 'mercury lynx l'],
       ['82', 'plymouth horizon miser'],
       ['82', 'mazda glc custom'],
       ['82', 'mazda glc custom l'],
       ['82', 'volkswagen rabbit l'],
       ['82', 'amc concord dl'],
       ['82', 'ford fairmont futura'],
       ['82', 'pontiac phoenix'],
       ['82', 'dodge aries se'],
       ['82', 'pontiac j2000 se hatchback'],
     

In [545]:
for i in range(5):
    print(desc_sorted_model_year_car_name_data[i][1])

chevy s-10
ford ranger
dodge rampage
vw pickup
ford mustang gl


## 9. Correlation
Compute the Pearson correlation coefficient between mpg and weight using NumPy.

In [546]:
print("Pearson Correlation Coefficient = \n", np.corrcoef(mpg_data, weight_data))

Pearson Correlation Coefficient = 
 [[ 1.         -0.83174093]
 [-0.83174093  1.        ]]


## 10. Conditional Aggregates
Calculate the mean mpg for cars grouped by the number of cylinders using NumPy techniques.

In [547]:
np.column_stack(([mpg_data, cylinder_data]))

array([[18. ,  8. ],
       [15. ,  8. ],
       [18. ,  8. ],
       [16. ,  8. ],
       [17. ,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [15. ,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [24. ,  4. ],
       [22. ,  6. ],
       [18. ,  6. ],
       [21. ,  6. ],
       [27. ,  4. ],
       [26. ,  4. ],
       [25. ,  4. ],
       [24. ,  4. ],
       [25. ,  4. ],
       [26. ,  4. ],
       [21. ,  6. ],
       [10. ,  8. ],
       [10. ,  8. ],
       [11. ,  8. ],
       [ 9. ,  8. ],
       [27. ,  4. ],
       [28. ,  4. ],
       [25. ,  4. ],
       [25. ,  4. ],
       [19. ,  6. ],
       [16. ,  6. ],
       [17. ,  6. ],
       [19. ,  6. ],
       [18. ,  6. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [12. ,  8. ],
       [13. ,  8. ],
       [13. ,  8. ],
       [18. ,  6. ],
       [22. ,  4. ],
       [19. ,

In [548]:
np.unique(np.delete(np.column_stack(([mpg_data, cylinder_data])), 0, 1))

array([3., 4., 5., 6., 8.])

In [549]:
np.argsort(groups)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

# Pandas Problems

In [550]:
import pandas as pd

## 1. Basic Exploration
Load the dataset into a Pandas DataFrame. Display:
- The first 10 rows
- The total number of rows and columns
- Summary statistics for numerical columns

In [551]:
df = pd.read_csv("auto-mpg.csv")

In [552]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [553]:
df['horsepower'] = df['horsepower'].apply(pd.to_numeric, errors='coerce')
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [554]:
# First 10 rows
df.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   
5  15.0          8         429.0       198.0    4341          10.0   
6  14.0          8         454.0       220.0    4354           9.0   
7  14.0          8         440.0       215.0    4312           8.5   
8  14.0          8         455.0       225.0    4425          10.0   
9  15.0          8         390.0       190.0    3850           8.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino  
5          70       1           ford galaxie 500  
6          70       1           chevrolet impala  
7          70       1          plymouth fury iii  
8          70       1           pontiac catalina  
9          70       1         amc ambassador dpl

In [555]:
# Total number of rows and columns
print("No. of rows = ", df.shape[0])
print("No. of columns = ", df.shape[1])

No. of rows =  398
No. of columns =  9


In [556]:
# Summary statistics for numerical columns
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

## 2. Filtering and Indexing
Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.

In [557]:
filtered_df = df[(df["model year"]==75) & (df["weight"]<3000)]
filtered_df[["car name","weight","mpg"]]

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

## 3. Handling Missing Data
Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [558]:
df.isna().any()

mpg             False
cylinders       False
displacement    False
horsepower       True
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [559]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

In [560]:
df.isna().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

## 4. Data Transformation
Add a new column power_to_weight_ratio, calculated as horsepower/weight.

In [561]:
df['power_to_weight_ratio'] = df['horsepower']/df['weight']

In [562]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  
0            70       1  chevrolet chevelle malibu               0.037100  
1            70       1          buick skylark 320               0.044679  
2            70       1         plymouth satellite               0.043655  
3            70       1              amc rebel sst               0.043694  
4            70       1                ford torino               0.040591  
..          ...     ...                        ...                    ...  
393          82       1            ford mustang gl               0.030824  
394          82       2                  vw pickup               0.024413  
395          82       1              dodge rampage               0.036601  
396          82       1                ford ranger               0.030095  
397          82       1                 chevy s-10               0.030147  

[398 rows x 10 columns]

## 5. Group By
Group the cars by origin and calculate the mean mpg for each group.

In [563]:
group = df.groupby(['origin'])

In [564]:
group['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

## 6. Sorting
Sort the DataFrame by mpg in descending order and display the top 10 cars withthe highest mpg.

In [565]:
df.sort_values(by='mpg', ascending=False).head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0   65.000000    2110          17.9   
329  44.6          4          91.0   67.000000    1850          13.8   
325  44.3          4          90.0   48.000000    2085          21.7   
394  44.0          4          97.0   52.000000    2130          24.6   
326  43.4          4          90.0   48.000000    2335          23.7   
244  43.1          4          90.0   48.000000    1985          21.5   
309  41.5          4          98.0   76.000000    2144          14.7   
330  40.9          4          85.0  104.469388    1835          17.3   
324  40.8          4          85.0   65.000000    2110          19.2   
247  39.4          4          85.0   70.000000    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.056932  
324               0.030806  
247               0.033816

## 7. Apply Function
Create a new column performance_score using a custom function:  
`def performance_score(row):`  
`  return row['mpg'] * row['acceleration'] / row['weight']`  
Apply this function to each row and store the result in the new column.

In [566]:
def performance_score(row):
    return row['mpg']*row['acceleration']/row['weight']

In [567]:
df['performance_score']=performance_score(df)

In [568]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0             0.061644  
1             0.046710  
2             0.057625  
3             0.055928  
4             0.051754  
..                 ...  
393           0.150968  
394           0.508169  
395           0.161743  
396           0.198400  
397           0.221103  

[398 rows x 11 columns]

## 8. Visualization Preparation
Generate a summary DataFrame with:
- Average mpg, weight, and horsepower for each model_year.

In [569]:
summary_df = df.groupby('model year')[['mpg','weight','horsepower']].mean()

In [570]:
summary_df

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.945335
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.609977
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   79.342716
81          30.334483  2522.931034   81.843772
82          31.709677  2453.548387   82.208690

## 9. Exporting Data
Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [571]:
subset_df = df[df['mpg']>30]
subset_df[['mpg','cylinders','horsepower','weight']]

mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]

In [572]:
subset_df[['mpg','cylinders','horsepower','weight']].to_csv('high_mpg_cars.csv')

In [573]:
verify_df = pd.read_csv('high_mpg_cars.csv')
verify_df.head()

Unnamed: 0   mpg  cylinders  horsepower  weight
0          53  31.0          4        65.0    1773
1          54  35.0          4        69.0    1613
2         129  31.0          4        67.0    1950
3         131  32.0          4        65.0    1836
4         144  31.0          4        52.0    1649

## 10. Finding Anomalies
Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically:
- Calculate the IQR for mpg.
- Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.
- Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
and model_year.

In [574]:
# IQR for mpg
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3-Q1
print("Q1 of mpg = ", Q1)
print("Q3 of mpg = ", Q3)
print("IQR of mpg = ", IQR)

Q1 of mpg =  17.5
Q3 of mpg =  29.0
IQR of mpg =  11.5


In [575]:
# Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.
outliers = (df['mpg']<(Q1 - 1.5 * IQR)) | (df['mpg']>(Q3 + 1.5 * IQR))
print("Outliers are mpg <",Q1 - 1.5 * IQR, "or mpg >", Q3 + 1.5 * IQR)

Outliers are mpg < 0.25 or mpg > 46.25


In [576]:
# Create a DataFrame of cars classified as outliers, displaying car_name, mpg, and model_year.
outlier_df = df[outliers]
outlier_df[['car name','mpg','model year']]

car name   mpg  model year
322  mazda glc  46.6          80