# NumPy and Pandas

In [2]:
import numpy as np

In [3]:
x = np.arange(1,100)
np.std(x)

28.577380332470412

In [4]:
np.random.random(4)

array([0.55161611, 0.88451096, 0.36778826, 0.05945769])

In [5]:
np.random.randn(4)

array([1.14947919, 0.7519652 , 0.04689184, 0.26933347])

In [6]:
np.random.randint(1,11,4)

array([6, 3, 3, 2])

In [7]:
a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [8]:
a = np.arange(10, dtype=np.float64)
print(a)
a.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [9]:
np.array([1+3j]).dtype

dtype('complex128')

In [10]:
np.array([True, False]).dtype

dtype('bool')

In [11]:
np.array(["Hello", "World!"]).dtype

dtype('<U6')

In [12]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
x[98] = 1000
print(x)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
 1000]


In [14]:
y = x[::2]
y

array([   1,    3,    5,    7,    9,   11,   13,   15,   17,   19,   21,
         23,   25,   27,   29,   31,   33,   35,   37,   39,   41,   43,
         45,   47,   49,   51,   53,   55,   57,   59,   61,   63,   65,
         67,   69,   71,   73,   75,   77,   79,   81,   83,   85,   87,
         89,   91,   93,   95,   97, 1000])

In [15]:
x[::-2]

array([1000,   97,   95,   93,   91,   89,   87,   85,   83,   81,   79,
         77,   75,   73,   71,   69,   67,   65,   63,   61,   59,   57,
         55,   53,   51,   49,   47,   45,   43,   41,   39,   37,   35,
         33,   31,   29,   27,   25,   23,   21,   19,   17,   15,   13,
         11,    9,    7,    5,    3,    1])

In [16]:
x[::2][::-1]

array([1000,   97,   95,   93,   91,   89,   87,   85,   83,   81,   79,
         77,   75,   73,   71,   69,   67,   65,   63,   61,   59,   57,
         55,   53,   51,   49,   47,   45,   43,   41,   39,   37,   35,
         33,   31,   29,   27,   25,   23,   21,   19,   17,   15,   13,
         11,    9,    7,    5,    3,    1])

In [17]:
x[::2][::-1][::-1]

array([   1,    3,    5,    7,    9,   11,   13,   15,   17,   19,   21,
         23,   25,   27,   29,   31,   33,   35,   37,   39,   41,   43,
         45,   47,   49,   51,   53,   55,   57,   59,   61,   63,   65,
         67,   69,   71,   73,   75,   77,   79,   81,   83,   85,   87,
         89,   91,   93,   95,   97, 1000])

In [18]:
np.shares_memory(x,y)

True

In [19]:
z = x[::2].copy()
z

array([   1,    3,    5,    7,    9,   11,   13,   15,   17,   19,   21,
         23,   25,   27,   29,   31,   33,   35,   37,   39,   41,   43,
         45,   47,   49,   51,   53,   55,   57,   59,   61,   63,   65,
         67,   69,   71,   73,   75,   77,   79,   81,   83,   85,   87,
         89,   91,   93,   95,   97, 1000])

In [20]:
np.shares_memory(x,z)

False

In [21]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
b = np.arange(7,13).reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
vertical_stack = np.vstack((a,b))
vertical_stack

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
horizontal_stack = np.hstack((a,b))
horizontal_stack

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [25]:
vertical_concat = np.concatenate([a,b], axis=1)
vertical_concat

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [26]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [27]:
np.dot(a, a.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [28]:
import pandas as pd

In [29]:
weather_data = {("1/1/2024",32,6,"rain"),
               ("2/1/2024",35,7,"sunny")}

In [30]:
df = pd.DataFrame(weather_data, 
                  columns=["Date","Temp","Wind","Climate"])
df

Date  Temp  Wind Climate
0  2/1/2024    35     7   sunny
1  1/1/2024    32     6    rain

In [31]:
df.shape

(2, 4)

In [32]:
df.head

<bound method NDFrame.head of        Date  Temp  Wind Climate
0  2/1/2024    35     7   sunny
1  1/1/2024    32     6    rain>

In [33]:
df = pd.read_csv("auto-mpg.csv")

In [37]:
df.shape

(398, 9)

In [40]:
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [41]:
df.tail(2)

mpg  cylinders  displacement horsepower  weight  acceleration  \
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin     car name  
396          82       1  ford ranger  
397          82       1   chevy s-10

In [44]:
df["mpg"]

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [45]:
df.mpg

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [50]:
df[["mpg", "car name"]]

mpg                   car name
0    18.0  chevrolet chevelle malibu
1    15.0          buick skylark 320
2    18.0         plymouth satellite
3    16.0              amc rebel sst
4    17.0                ford torino
..    ...                        ...
393  27.0            ford mustang gl
394  44.0                  vw pickup
395  32.0              dodge rampage
396  28.0                ford ranger
397  31.0                 chevy s-10

[398 rows x 2 columns]

In [49]:
df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [39]:
df.describe

<bound method NDFrame.describe of       mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1      

In [51]:
new_df = df[["mpg", "car name"]]

In [55]:
new_df.to_csv("new-auto-mpg.csv")

In [56]:
df.sample(10)

mpg  cylinders  displacement horsepower  weight  acceleration  \
184  25.0          4         140.0         92    2572          14.9   
347  37.0          4          85.0         65    1975          19.4   
340  25.8          4         156.0         92    2620          14.4   
121  15.0          8         318.0        150    3399          11.0   
71   19.0          3          70.0         97    2330          13.5   
269  30.9          4         105.0         75    2230          14.5   
81   28.0          4          97.0         92    2288          17.0   
34   16.0          6         225.0        105    3439          15.5   
260  18.6          6         225.0        110    3620          18.7   
395  32.0          4         135.0         84    2295          11.6   

     model year  origin                   car name  
184          76       1                   capri ii  
347          81       3             datsun 210 mpg  
340          81       1     dodge aries wagon (sw)  
121          73       1          dodge dart custom  
71           72       3            mazda rx2 coupe  
269          78       1                 dodge omni  
81           72       3            datsun 510 (sw)  
34           71       1  plymouth satellite custom  
260          78       1                dodge aspen  
395          82       1              dodge rampage

In [57]:
df.sample(frac=0.2)

mpg  cylinders  displacement horsepower  weight  acceleration  \
283  20.2          6         232.0         90    3265          18.2   
100  18.0          6         250.0         88    3021          16.5   
280  21.5          6         231.0        115    3245          15.4   
209  19.0          4         120.0         88    3270          21.9   
49   23.0          4         122.0         86    2220          14.0   
..    ...        ...           ...        ...     ...           ...   
11   14.0          8         340.0        160    3609           8.0   
143  26.0          4          97.0         78    2300          14.5   
233  29.0          4          97.0         78    1940          14.5   
380  36.0          4         120.0         88    2160          14.5   
316  19.1          6         225.0         90    3381          18.7   

     model year  origin                  car name  
283          79       1          amc concord dl 6  
100          73       1             ford maverick  
280          79       1         pontiac lemans v6  
209          76       2               peugeot 504  
49           71       1        mercury capri 2000  
..          ...     ...                       ...  
11           70       1        plymouth 'cuda 340  
143          74       2                opel manta  
233          77       2  volkswagen rabbit custom  
380          82       3          nissan stanza xe  
316          80       1               dodge aspen  

[80 rows x 9 columns]

In [60]:
g = df.groupby("model year")
g

In [62]:
g.max()

mpg  cylinders  displacement horsepower  weight  acceleration  \
model year                                                                   
70          27.0          8         455.0         97    4732          20.5   
71          35.0          8         400.0          ?    5140          20.5   
72          28.0          8         429.0         97    4633          23.5   
73          29.0          8         455.0         95    4997          21.0   
74          32.0          8         350.0          ?    4699          21.0   
75          33.0          8         400.0         98    4668          21.0   
76          33.0          8         351.0         95    4380          22.2   
77          36.0          8         400.0         98    4335          19.0   
78          43.1          8         318.0         97    4080          21.5   
79          37.3          8         360.0         90    4360          24.8   
80          46.6          6         225.0          ?    3381          23.7   
81          39.1          8         350.0          ?    3725          20.7   
82          44.0          6         262.0          ?    3035          24.6   

            origin                      car name  
model year                                        
70               3  volkswagen 1131 deluxe sedan  
71               3          volkswagen model 111  
72               3               volvo 145e (sw)  
73               3                   volvo 144ea  
74               3             volkswagen dasher  
75               3                   volvo 244dl  
76               3                     vw rabbit  
77               3      volkswagen rabbit custom  
78               3                   volvo 264gl  
79               3              vw rabbit custom  
80               3          vw rabbit c (diesel)  
81               3                  volvo diesel  
82               3                     vw pickup

In [74]:
us_weather = pd.DataFrame({
    "city":["NY","Chicago","Seatle"],
    "Temp":[21,15,35],
    "Humidity":[68,65,75]
})
us_weather

city  Temp  Humidity
0       NY    21        68
1  Chicago    15        65
2   Seatle    35        75

In [75]:
india_weather = pd.DataFrame({
    "city":["Kerala","Goa","Delhi"],
    "Temp":[37,21,35],
    "Humidity":[64,69,58]
})
india_weather

city  Temp  Humidity
0  Kerala    37        64
1     Goa    21        69
2   Delhi    35        58

In [76]:
weather_us_india = pd.concat([us_weather, india_weather], ignore_index=True)
weather_us_india

city  Temp  Humidity
0       NY    21        68
1  Chicago    15        65
2   Seatle    35        75
3   Kerala    37        64
4      Goa    21        69
5    Delhi    35        58

In [77]:
weather_us_india["Temp"]<30

0     True
1     True
2    False
3    False
4     True
5    False
Name: Temp, dtype: bool

In [78]:
weather_us_india[weather_us_india["Temp"]<30]

city  Temp  Humidity
0       NY    21        68
1  Chicago    15        65
4      Goa    21        69

In [79]:
pd.concat([us_weather, india_weather], axis=1)

city  Temp  Humidity    city  Temp  Humidity
0       NY    21        68  Kerala    37        64
1  Chicago    15        65     Goa    21        69
2   Seatle    35        75   Delhi    35        58

In [83]:
pd.merge(us_weather, india_weather, on="Temp")

city_x  Temp  Humidity_x city_y  Humidity_y
0      NY    21          68    Goa          69
1  Seatle    35          75  Delhi          58

In [88]:
df_index = pd.DataFrame([1,2,3,4], index=[49,48,12,3])
df_index

0
49  1
48  2
12  3
3   4

In [93]:
df_index.loc[49]

0    1
Name: 49, dtype: int64

In [94]:
df_index.iloc[2]

0    3
Name: 12, dtype: int64

In [103]:
city1 = pd.Series([12, -6,8,-3], index=["day1", "day2", "day3", "day4"])
city1

day1    12
day2      
day3     8
day4    -3
dtype: object

In [104]:
city1.isna()

day1    False
day2    False
day3    False
day4    False
dtype: bool

In [97]:
city1.isna().sum()

0

In [105]:
df["car name"].unique()

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'chevrolet vega 2300', 'toyota corona',
       'ford pinto', 'plymouth satellite custom', 'ford torino 500',
       'amc matador', 'pontiac catalina brougham', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
       'pontiac firebird', 'ford mustang', 'mercury capri 2000',
       'opel 1900'

In [107]:
df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [112]:
new_cars = df.drop(["origin","car name"], axis=1)
new_cars

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]